services:
  postgres:
    image: postgres:15.3
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car_shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network


  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat_server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - network


volumes:
  postgres_data:

networks:
  network: